[package]
name = "powershell"
version = "0.2.0"
edition = "2021"
description = "invoke PowerShell from Rust"
license = "MIT"
repository = "https://github.com/onxcy/powershell"

[dependencies]
base64 = "0.22.1"
bytemuck = "1.20.0"
